<?php
/**
 * Copyright © Panth Infotech. All rights reserved.
 *
 * @var $block \Panth\LowStockNotification\Block\Adminhtml\Alert\Edit
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<button type="button" id="back" class="action-default scalable back"
        title="<?= $escaper->escapeHtmlAttr(__('Back')) ?>"
        onclick="setLocation('<?= $escaper->escapeJs($block->getBackUrl()) ?>')">
    <span><?= $escaper->escapeHtml(__('Back')) ?></span>
</button>
<button type="submit" id="lsn-alert-delete" class="action-default scalable delete" form="lsn-alert-delete-form"
        title="<?= $escaper->escapeHtmlAttr(__('Delete')) ?>">
    <span><?= $escaper->escapeHtml(__('Delete')) ?></span>
</button>
<?php if ($block->canSendEmail()): ?>
<button type="submit" id="lsn-alert-send" class="action-default scalable save primary" form="lsn-alert-send-form"
        title="<?= $escaper->escapeHtmlAttr(__('Send Email')) ?>">
    <span><?= $escaper->escapeHtml(__('Send Email')) ?></span>
</button>
<?php endif; ?>
